# Generated by Django 4.1.5 on 2023-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_token',
            field=models.CharField(default='', max_length=32, verbose_name='Телеграм токен'),
            preserve_default=False,
        ),
    ]
