# Generated by Django 4.1.5 on 2023-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_telegram_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='Телеграм токен'),
        ),
    ]
