# Generated by Django 4.1.5 on 2023-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_telegram_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телеграм токен'),
        ),
    ]
