# Generated by Django 4.1.5 on 2023-01-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_telegram_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='chat_id'),
        ),
    ]
