# Generated by Django 4.1.5 on 2023-09-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.PositiveIntegerField(verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на детальную страницу')),
                ('views', models.PositiveIntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
