# Generated by Django 4.1.5 on 2023-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='page_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Идентификатор'),
        ),
    ]
