# Generated by Django 4.1.5 on 2023-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_ads_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
    ]
