# Generated by Django 4.1.5 on 2023-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300, verbose_name='Фраза')),
                ('translate', models.CharField(max_length=300, verbose_name='Перевод фразы')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
        migrations.RemoveField(
            model_name='words',
            name='phrases',
        ),
    ]
