# Generated by Django 4.1.5 on 2023-04-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_phrases_remove_words_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='phrases',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.phrases', verbose_name='Фраза'),
            preserve_default=False,
        ),
    ]
