# Generated by Django 4.1.5 on 2023-04-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_words_phrases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='phrases',
        ),
        migrations.AddField(
            model_name='phrases',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='words.words'),
            preserve_default=False,
        ),
    ]
