# Generated by Django 4.1.5 on 2023-04-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_phrases_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedword', to='words.words'),
        ),
    ]
