# Generated by Django 4.1.5 on 2023-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Старт')),
                ('arrived', models.DateTimeField(blank=True, null=True, verbose_name='Прибыл')),
                ('process', models.DateTimeField(blank=True, null=True, verbose_name='В процессе')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Завершил')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('payment_type', models.CharField(blank=True, choices=[(1, 'Наличные'), (2, 'Карта'), (3, 'Каспи')], max_length=100, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[(1, 'Принят'), (3, 'Выполнен'), (4, 'Отменён')], default=1, max_length=100, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
