# Generated by Django 4.1.5 on 2023-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Наличные'), (2, 'Карта'), (3, 'Каспи')], verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Принят'), (3, 'Выполнен'), (4, 'Отменён')], default=1, verbose_name='Статус заявки'),
        ),
    ]
