# Generated by Django 4.1.5 on 2023-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_tax_payment_type_alter_tax_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Наличные'), (2, 'Карта'), (3, 'Каспи')], null=True, verbose_name='Тип оплаты'),
        ),
    ]
