# Generated by Django 4.1.5 on 2023-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_tax_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
